### ISSUE TITLE
error on consul server

### ISSUE THREAD

**Issue by buluxan** [testdrivenio/vault-consul-swarm#2]
hi does the consul script put on swarm production is it good or not ?
i have just tried using your consul script and i'm combine using my registrator script its working but when i tried scale consul server became 5 i got and error 

    2018/09/29 03:14:02 [INFO] serf: attempting reconnect to 7a85853e6ef9.dc1 10.0.1.16:8302
    2018/09/29 03:14:00 [ERR] agent: failed to sync remote state: No cluster leader
question :
is it possible to put consul server on swarm 

here's my consule screenshoot 

![screen shot 2018-09-29 at 10 17 49 am](https://user-images.githubusercontent.com/7418412/46240397-fe306b00-c3d0-11e8-949f-b63cdba720e8.png)

**Comment by mjhea0** [comment]
is this still an issue?
